### ISSUE TITLE
代码问题，无法训练

### ISSUE THREAD

**Issue by MrDec** [wcyjerry/BasicISOS#3]
2024-01-26 15:40:47,828 INFO: training from epoch: 1
Traceback (most recent call last):
  File "/home/dww/OD/BasicISOS/train.py", line 172, in <module>
    main()
  File "/home/dww/OD/BasicISOS/train.py", line 139, in main
    for idx, data in enumerate(test_loader):
  File "/home/dww/anaconda3/envs/detection/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/dww/anaconda3/envs/detection/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/dww/anaconda3/envs/detection/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dww/anaconda3/envs/detection/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dww/OD/BasicISOS/basicseg/data/load_data.py", line 40, in __getitem__
    aug_inputs = transform_fn(image=img, mask=mask)
  File "/home/dww/anaconda3/envs/detection/lib/python3.8/site-packages/albumentations/core/composition.py", line 195, in __call__
    self._check_args(**data)
  File "/home/dww/anaconda3/envs/detection/lib/python3.8/site-packages/albumentations/core/composition.py", line 286, in _check_args
    raise ValueError(
ValueError: Height and Width of image, mask or masks should be equal. You can disable shapes check by setting a parameter is_check_shapes=False of Compose class (do it only if you are sure about your data consistency).

**Comment by KeanuWongves** [comment]
看看你的yaml文件中的配置
